version: "3"

services:

  db:
    image: apiphp_new3:latest
    command: --default-authentication-plugin=mysql_native_password
    container_name: apiphpnew3_name
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: desenvolvedores
      MYSQL_USER: root
      MYSQL_PASSWORD: root123
    command: --init-file /var/www/html/apiphp/db.sql
    #volumes:
      #- dbdata:/var/lib/mysql
      #- ./apiphp/db.sql:/data/application/init.sql
    ports:
      - "6033:3306"
